spring.application.name=chatbot
server.port=${PORT:8081}
server.address=0.0.0.0

# MySQL Database Configuration
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chatbot_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ANUmitobi18!!}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:chatbot_db;MODE=MySQL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Disable open-view warning
spring.jpa.open-in-view=false

# Python Emotion Service
emotion.service.url=${EMOTION_SERVICE_URL:https://mindease-ai.pxxl.run}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
